#!/usr/bin/env python
import sys
for arg in reversed(sys.argv[1:]):
    print(arg)

# python 脚本，逆序输出脚本全部参数
# 修改本文件 chmod 755，python 脚本也可以在 bash 中直接运行
# shell知道去用python解释器而不是shell命令来运行这段脚本，是因为脚本的开头第一行的shebang。
# https://en.wikipedia.org/wiki/Shebang_(Unix)
# env 会利用我们第一节讲座中介绍过的 PATH 环境变量来进行定位。



